[versions]
coroutines = "1.9.0"
dependency-check = "11.1.0"
sonarqube = "5.1.0.4882"
kotlin = "2.0.21"
spotless = "6.25.0"
nimbus-sdk = "11.6"
ktor = "3.0.1"
jsoup = "1.18.1"
cbor = "0.9"
java = "17"
ktlint = "0.50.0"
dokka = "1.9.20"
maven-publish = "0.30.0"
logback = "1.5.12"

[libraries]
nimbus-oauth2-oidc-sdk = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbus-sdk" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-logging = {module ="io.ktor:ktor-client-logging", version.ref="ktor"}
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
cbor = { module = "co.nstant.in:cbor", version.ref = "cbor" }
logback-classic = {module="ch.qos.logback:logback-classic", version.ref="logback"}

[plugins]
dependency-check = { id = "org.owasp.dependencycheck", version.ref = "dependency-check" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref="maven-publish" }
